export const SET_CURRENT_USER = 'SET CURRENT USER';

export const LOAD_COMMENTS = 'LOAD COMMENTS';
export const LOAD_COMMENTS_SUCCESS = 'LOAD COMMENTS SUCCESS';
export const LOAD_COMMENTS_FAILED = 'LOAD COMMENTS FAILED';

export const SAVE_COMMENT = 'SAVE COMMENT';
export const SAVE_COMMENT_SUCCESS = 'SAVE COMMENT_SUCCESS';
export const SAVE_COMMENT_FAILED = 'SAVE COMMENT_FAILED';
