export const LOAD_COMMENTS = 'LOAD COMMENTS';
export const LOAD_COMMENTS_SUCCESS = 'LOAD COMMENTS SUCCESS';
export const LOAD_COMMENTS_FAILED = 'LOAD COMMENTS FAILED';

export const SAVE_COMMENT = 'SAVE COMMENT';
export const SAVE_COMMENT_SUCCESS = 'SAVE COMMENT_SUCCESS';
export const SAVE_COMMENT_FAILED = 'SAVE COMMENT_FAILED';

export const LOAD_REPLY_COMMENTS = 'LOAD REPLY COMMENTS';
export const LOAD_REPLY_COMMENTS_SUCCESS = 'LOAD REPLY COMMENTS SUCCESS';
export const LOAD_REPLY_COMMENTS_FAILED = 'LOAD REPLY COMMENTS FAILED';

export const SAVE_REPLY_COMMENT = 'SAVE REPLY COMMENT';
export const SAVE_REPLY_COMMENT_SUCCESS = 'SAVE REPLY COMMENT_SUCCESS';
export const SAVE_REPLY_COMMENT_FAILED = 'SAVE REPLY COMMENT_FAILED';
