export const GET_COMMENTS = 'GET COMMENTS';
export const GET_COMMENTS_SUCCESS = 'GET COMMENTS SUCCESS';
export const GET_COMMENTS_FAILED = 'GET COMMENTS FAILED';

export const SAVE_COMMENT = 'SAVE COMMENT';
export const SAVE_COMMENT_SUCCESS = 'SAVE COMMENT_SUCCESS';
export const SAVE_COMMENT_FAILED = 'SAVE COMMENT_FAILED';

export const SAVE_REPLY_COMMENT = 'SAVE REPLY COMMENT';
export const SAVE_REPLY_COMMENT_SUCCESS = 'SAVE REPLY COMMENT_SUCCESS';
export const SAVE_REPLY_COMMENT_FAILED = 'SAVE REPLY COMMENT_FAILED';
